dist: xenial
language: python
python: 3.7

install:
  - pip install kodi-addon-checker

before_script:
- git config core.quotepath false

# command to run our tests
script:
  - kodi-addon-checker --branch=leia .

notifications:
  webhooks: https://www.travisbuddy.com/
  email:
    on_failure: change # default: always
